package ru;

import javax.swing.*;
import java.awt.*;

public class MainForm {
    JPanel mainPanel;
    JLabel imageLabel;
    private AthomPanel athomPanel;
    private JButton calcButton;
    private JCheckBox checkBox;

    public void initImageLabel() {
        double scale = 0.5;
        Image img = new ImageIcon("src/ru/scheme.jpg").getImage();
        imageLabel.setIcon(new ImageIcon(img));
        int newW = (int) (imageLabel.getIcon().getIconWidth() * scale);
        int newH = (int) (imageLabel.getIcon().getIconHeight() * scale);
        img = img.getScaledInstance(newW, newH, Image.SCALE_SMOOTH);
        imageLabel.setIcon(new ImageIcon(img));
    }

    public MainForm() {
        initImageLabel();

        Runnable task = () -> {
            String threadName = Thread.currentThread().getName();
            while (checkBox.isSelected()) {
                //System.out.println("Hello " + threadName);
                athomPanel.calc();
                try {
                    Thread.sleep(100);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
            }
        };
        //task.run();

        calcButton.addActionListener(actionEvent -> {
            Thread thread = new Thread(task);
            thread.start();
        });
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1));
        imageLabel = new JLabel();
        imageLabel.setHorizontalAlignment(0);
        imageLabel.setHorizontalTextPosition(0);
        imageLabel.setText("");
        mainPanel.add(imageLabel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_NORTHWEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        athomPanel = new AthomPanel();
        athomPanel.setLayout(new BorderLayout(0, 0));
        mainPanel.add(athomPanel, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        athomPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), null));
        final JToolBar toolBar1 = new JToolBar();
        toolBar1.setBorderPainted(false);
        toolBar1.setFloatable(false);
        mainPanel.add(toolBar1, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(-1, 20), null, 0, false));
        calcButton = new JButton();
        calcButton.setText("Calc");
        toolBar1.add(calcButton);
        checkBox = new JCheckBox();
        checkBox.setSelected(true);
        checkBox.setText("CheckBox");
        toolBar1.add(checkBox);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
