import javax.imageio.ImageIO;
import javax.swing.*;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.io.InputStream;

public class MainForm {
    JPanel mainPanel;
    JLabel imageLabel;
    private AthomPanel athomPanel;
    private JButton gasButton;
    private JButton breakButton;
    private boolean isStarted = false;

    public void showPicture() {
        double scale = 0.5;
        InputStream is = getClass().getClassLoader().getResourceAsStream("jpg/scheme.jpg");
        BufferedImage image = null;
        try {
            image = ImageIO.read(is);
            imageLabel.setIcon(new ImageIcon(image));
            int newW = (int) (imageLabel.getIcon().getIconWidth() * scale);
            int newH = (int) (imageLabel.getIcon().getIconHeight() * scale);
            Image imag = image.getScaledInstance(newW, newH, Image.SCALE_SMOOTH);
            imageLabel.setIcon(new ImageIcon(imag));
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    public MainForm() {
        showPicture();

        Runnable task = () -> {
            while (isStarted) {
                athomPanel.doSomeThing();
                try {
                    Thread.sleep(100);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
            }
        };

        gasButton.addActionListener(actionEvent -> {
            isStarted = true;
            new Thread(task).start();
            gasButton.setText(gasButton.getText() + ">");
            //athomPanel.doSomeThing();
        });

        breakButton.addActionListener(actionEvent -> {
            isStarted = false;
            gasButton.setText("Gas ");
        });

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1));
        imageLabel = new JLabel();
        imageLabel.setHorizontalAlignment(0);
        imageLabel.setHorizontalTextPosition(0);
        imageLabel.setText("");
        mainPanel.add(imageLabel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_SOUTHWEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        athomPanel = new AthomPanel();
        athomPanel.setLayout(new BorderLayout(0, 0));
        mainPanel.add(athomPanel, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        athomPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), null));
        final JToolBar toolBar1 = new JToolBar();
        toolBar1.setBorderPainted(false);
        toolBar1.setFloatable(false);
        mainPanel.add(toolBar1, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(-1, 20), null, 0, false));
        gasButton = new JButton();
        gasButton.setText("Gas ");
        toolBar1.add(gasButton);
        final com.intellij.uiDesigner.core.Spacer spacer1 = new com.intellij.uiDesigner.core.Spacer();
        toolBar1.add(spacer1);
        breakButton = new JButton();
        breakButton.setText("Break");
        toolBar1.add(breakButton);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
